[tool.poetry]
name = "grii-europe-slide-maker"
version = "0.1.0"
description = ""
authors = ["stepkurniawan <stepkurniawan@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
streamlit = "^1.47.0"
requests = "^2.32.4"
python-pptx = "^1.0.2"
protobuf = "^6.31.1"
google-auth-oauthlib = "^1.2.2"
google-api-python-client = "^2.177.0"
htbuilder = "0.6.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
